### ISSUE TITLE
DefaultButtonIconProfileFont keep loses assigned HoloSymMDL2 font

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MRDesignLabs_Unity#12]
DefaultButtonIconProfileFont randomly loses assigned HoloSymMDL2 font which makes the App Bar buttons display placeholder icons. It keeps happening while iterating design & deploy. Re-assigning symbol font (with auto assign button) works well but the symptom comes again. (even though HoloSymMDL2 font file exist)

![2017-06-20 23_13_29-2017-06-20 23_01_30-greenshot png - photos](https://user-images.githubusercontent.com/13754172/27369729-1cf90d58-560e-11e7-9463-aac5d448b5fa.png)

**Comment by Railboy** [comment]
The inspector wasn't forcing unity to save its changes. This has been fixed.
