### ISSUE TITLE
Can't compile - 'Type' does not contain a definition for 'GetFields'

### ISSUE THREAD

**Issue by MarcPilgaard** [Microsoft/MRDesignLabs_Unity#13]
I can't compile MRDesignLabs due to:

Assets\MRDesignLab\HUX\Scripts\Buttons\ButtonIconProfileTexture.cs(60,45): error CS1061: 'Type' does not contain a definition for 'GetFields' and no extension method 'GetFields' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

From my understanding it appears the repo is using some reflection methods which are unsupported in the Windows .NET implementation.

I am running Unity 5.6.1p3 and I have previously build to Hololens on other projects with any problems. I have the most recent commit of MRDesignLabs. I have selected API Compatibility to 4.6 in player settings, and are using .NET as scripting backend.

**Comment by Railboy** [comment]
You are correct. I've cordoned off this code with preprocessor directives. Let us know if it still gives you trouble.
