### ISSUE TITLE
Project should be organized with sub modules

### ISSUE THREAD

**Issue by Railboy** [Microsoft/MRDesignLabs_Unity#17]
Manually copying changes between the DesignLabs_Unity & DesignLabs_Unity_Examples projects is error-prone and time consuming. I'm also concerned about the PeriodicTable project (and other sample app projects) drifting out of sync with our primary HUX project.

We should set up a HUX sub-module to ensure parity and reduce workload: https://github.com/blog/2104-working-with-submodules

Since we're starting to see regular usage / contributions we should do this sooner rather than later to get any potential disruption out of the way.

**Comment by paseb** [comment]
Valid concern and where I wanted to head with the structure anyway. Checking in new repository for our Unity Tools.  Changes should be made in that repo ( https://github.com/Microsoft/MRDesignLabs_Unity_Tools.git
 ) and propagated from there.  I've replaced the submodules in bot DesignLabs_Unity as well as DesignLabs_Unity_Examples.

**Comment by paseb** [comment]
Changes have been pushed please do a pull and make sure it all looks good on your end.
