### ISSUE TITLE
Consider renaming ContextMenu.cs since it conflicts with UnityEngine.ContextMenu.

### ISSUE THREAD

**Issue by ei2kpi** [Microsoft/MRDesignLabs_Unity#23]
See UAudioManager.cs in the HoloToolkit\SpatialSound\Scripts\UAudioManager\ folder. Latest Holotoolkit reverts the attribute at the bottom to ContextMenu instead of UnityEngine.ContextMenu which is what prevents an error in MRDesignLabs_Unity

**Comment by paseb** [comment]
Hi @ei2kpi,

This has already been fixed in the main _Tools repo and just needs to be updated in this repo.  I'll update the submodules to reflect the change.

thanks,
-pat

**Comment by paseb** [comment]
They should all be updated if you update your submodules.  I had change d ContextMenu to "ContextMenuWidget" as that's really what it is and not a context menu per-se. 

thanks,
-pat
