### ISSUE TITLE
Bounding box not adapted for the 2D object ?

### ISSUE THREAD

**Issue by alelay** [Microsoft/MRDesignLabs_Unity#24]
Hello everyone !

When I attach the bounding box script to a thin object, the box is a little too big and the scale/rotate elements are too small and too far from the box.

![screen_4000x2250_2017-07-11_10-49-15](https://user-images.githubusercontent.com/27273586/28060875-dcc92b0c-6628-11e7-8d9c-8effe13f2e2b.png)
![screen_4000x2250_2017-07-11_10-49-24](https://user-images.githubusercontent.com/27273586/28060876-dce17e6e-6628-11e7-993a-ce61f5f135fe.png)

Do you have a solution to improve this?

Thanks!

**Comment by Railboy** [comment]
You can adjust the bounding box's 'ScalePadding' property of the BoundingBoxGizmo to make it fit more snugly.

**Comment by cre8ivepark** [comment]
@alelay @Railboy I am having similar issues on the scaling/rotating grabber size. For the objects with small scaling values, the grabber becomes very small and hard to interact with.
Also, it would be great if we can display only four grabbers for 2D objects just like the shell.

**Comment by paseb** [comment]
We should have a min clamp on size.  That's a good practice in general for interaction - angular scaling.

**Comment by Railboy** [comment]
I've added a min/max clamp - changes have been committed to the MRDesignLabs_Unity_Tools repo and will be propagated soon.

I'm also working on a '2D' bounding box mode that more closely mimics the shell. I'll keep this issue open until that's finished.

**Comment by alelay** [comment]
Nice, I go to see this !
Thanks

**Comment by Railboy** [comment]
The Bounding Box now has options for flattening axis, and it has a more accurate bounds detection mode for flat meshes.
