### ISSUE TITLE
Readme.md says that BoundingBox.prefab is necessary for AppBar + Bounding box interactble to work

### ISSUE THREAD

**Issue by ei2kpi** [Microsoft/MRDesignLabs_Unity#25]
In this Readme.md: https://github.com/Microsoft/MRDesignLabs_Unity/tree/master/DesignLabs_Unity_Examples

It looks like BoundingBox.prefab is no longer necessary to be put into the scene in order for AppBar + Bounding box to work. Also, BoundingBox.prefab no longer exists and seems to have been replaced by ShellBoundingBox and BasicBoundingBox. Now, it looks like BoundingBox target automatically instantiates the ShellBoundingBox

**Comment by Railboy** [comment]
Thanks for the heads up. I've updated the readme and will close this issue once it's been reviewed.

**Comment by cre8ivepark** [comment]
@ei2kpi @Railboy I'll review updated logic and related documents. Thanks!
