### ISSUE TITLE
Click 'Remove' button will destroy app bar, bounding box and even my cube object

### ISSUE THREAD

**Issue by williamye** [Microsoft/MRDesignLabs_Unity#28]
Hi everyone,

I attached bounding box script to a cube object following the instruction, and after I tapped the cube, I could scale/rotate the cube as expected, It worked perfectly. But when I clicked the 'Remove' button, I thought that it only destroyed the bounding box and tool bar. But the factor it destroyed the bounding box, tool bar and also the cube object.  Does it fit the design? Or I make some mistake. I did simple debug, found that OnDestroy function will be called, and boundingBox.Target = null. but the boundingBox.Target is my cube. So how can I only destroy the bounding box and tool bar, but keep my cube. And next I can tap the cube to scale/rotate again. Thank you.

**Comment by paseb** [comment]
Remove is meant to remove the object the same way it works in the shell.  If you want to just close/remove the bounding box you want to click **"Done"**.  Remove does in fact mean removing the object.  You can modify the code to do whatever you like when remove is clicked but the current behavior is as designed and in parity with the shell behaviors (except single objects go into adjust mode and not all of them like the shell).

thanks,
-pat

**Comment by williamye** [comment]
One more question, the behavior of "Done" is the same with "Show", The action are setting State = AppBarStateEnum.Default; in AppBar.cs. So after click the "Done", it will show default tool bar and also bounding box. In this case, it means that the current solution can't remove bounding box and tool bar, they are always there. If I want to keep the cube after adjust it, I should try to modify the code. Is that true? Thank you for your so quickly reply.

**Comment by paseb** [comment]
What it should do on "Done" is go back to the the default toolbar without the bounding box.  This is how the current shell works and should be the default behavior.  What is the behavior you're wanting for entering and exiting an adjust mode?

**Comment by williamye** [comment]
I want the function like this. The cube object in the scene, tap the cube, there is bounding box and tool bar, click the "Adjust", try to scale/rotate the cube, then click the "Done", remove the bounding box and tool bar, just keep the cube which has been adjusted. And if I want, I can tap the cube again to adjust it, then there should be a way to return to the original state. But current solution seems I can't return to the original state which only has cube object in my scene. There are always cube/bounding box/tool bar, click "Remove" then remove all. Meanwhile even I click the "Done", it still has tool bar and bounding box but this bounding box can't be edited. So should I modify the code to implement what I want?

**Comment by Railboy** [comment]
This only addresses part of your problem, but I've modified BoundingBoxGizmoShell so that it no longer shows a wireframe by default when manipulation is not active.

In the near future I will be adding a timeout feature to the app bar which fades out an 'inactive' bar if the user has not focused on the targeted object for a length of time.

If you want an explicit control to remove the app bar one option is to add a custom button using the app bar's editor interface and have a custom component listen for its Tapped message.

**Comment by williamye** [comment]
@Railboy  I see, thank you. I will try to add this custom button.
