### ISSUE TITLE
Bounding box wireframe for default state

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MRDesignLabs_Unity#29]
Currently, Bounding Box displays the wires in the default state. To align with shell's behavior, I recommend displaying the wires with grabbers in 'Adjust' mode only. Wires in default states can be confusing since it feels like it is interactable/draggable.

Suggested update (No wires in default state):
![holobarandboundingbox_hero2](https://user-images.githubusercontent.com/13754172/28279676-12b6c128-6ad6-11e7-9f17-39c20e4e9edb.jpg)

**Comment by Railboy** [comment]
Good suggestion, I've added this and updated the prefab.
