### ISSUE TITLE
Latest commits break Unity 5.6.x compatibility

### ISSUE THREAD

**Issue by connorjsmith** [Microsoft/MRDesignLabs_Unity#30]
Should probably mention that Unity 2017.x is the only supported version now that HoloToolKit was upgraded.

**Comment by paseb** [comment]
I've updated the markdown on the front page to reflect this.  We'll look at providing a set for tags based on the Unity version compatibility as well.

thanks,
-pat

**Comment by paseb** [comment]
I also added releases for previous versions of Unity.
