### ISSUE TITLE
Only Toolbar shown on Hololens (Interactable_Objects scene)

### ISSUE THREAD

**Issue by einstyle** [Microsoft/MRDesignLabs_Unity#31]
I´m running the Interactable_Objects scene but on Hololens I see only the toolbar, not other elements. Why?

**Comment by Railboy** [comment]
When you say other elements, do you mean the objects that you interact with, or the bounding box?

Are you able to see those elements in the editor, before building and deploying?

**Comment by Railboy** [comment]
Follow-up question: are you deploying a Release build or a Master build? In the past we've seen different behavior from some components depending on which build we deploy.
