### ISSUE TITLE
App Bar and Bounding Box example scene broken

### ISSUE THREAD

**Issue by skyworxx** [Microsoft/MRDesignLabs_Unity#34]
In the App Bar and Bounding Box example scene, the objects can't be manipulated.
When selecting an object, the app bar pops up (after a bit of lag) but the items don't do anything.
The issue can be seen here: https://youtu.be/fIb6vZiBnFM

I am getting following error when running in the editor:
"No target found for button Remove - button will have no effect."
Not exactly sure if it is related the problem or not.

Unity3d 2017 1.0f3
latest commits from repo

**Comment by Railboy** [comment]
Thanks for the heads up. This was related to a recent change we made to AppBar button initialization. A fix has been posted to MRDesignLabs_Unity_Tools. Let us know if you have any more trouble.
