### ISSUE TITLE
App Bar is not positioned correctly

### ISSUE THREAD

**Issue by o-mobile** [Microsoft/MRDesignLabs_Unity#36]
I have a rectangle shaped object (car) and I am using the App Bar and Bounding Box to manipulate the translation and rotation. When the App Bar is shown its not displayed correctly and displays inside of the car. Looking at the BoundingBoxShell Scale object this has the correct size, but it seems the App Bar is using wrong positions? Any suggestion on how to fix this.

**Comment by Railboy** [comment]
Does the object have a negative scale on any axis?

We recently added some options to the app bar that offer a degree of manual control over its positioning:
```
        /// <summary>
        /// Where to display the app bar on the y axis
        /// This can be set to negative values
        /// to force the app bar to appear below the object
        /// </summary>
        public float HoverOffsetYScale = 0.25f;

        /// <summary>
        /// Pushes the app bar away from the object
        /// </summary>
        public float HoverOffsetZ = 0f;
```
See if adjusting those helps.

**Comment by o-mobile** [comment]
This helps, but its still odd that the AppBar is not positioned on the edges of the bounding box. Surely thats a more desired approach?

**Comment by Railboy** [comment]
The App Bar should always appear on the outside of the object by default. Are you able to send a copy of your scene for me to take a look at? I'd like to check the scale of your object, and its mesh.

**Comment by o-mobile** [comment]
The content we are using is quite confidential, but I will see if I can replicate it with another project.

**Comment by Railboy** [comment]
Closing this for now - I'll re-open when we receive content to test.
