### ISSUE TITLE
The Interface/Hololens Prefab BoundingBoxShell is blocking Gaze 

### ISSUE THREAD

**Issue by waynebaby** [Microsoft/MRDesignLabs_Unity#39]
If your head position is not moving the cursor will show as "Hit something"

if the cam position is moved, the “hit cursor” is gone.

**Comment by Railboy** [comment]
This bug was fixed in a recent version of the MRDesignLabs_Unity_Tools submodule.

(If you're using the latest version let me know and I'll re-open this.)

**Comment by waynebaby** [comment]
@Railboy  hi

the bug is  still there

**Comment by Railboy** [comment]
Thanks for the update, I'll check this out.

**Comment by Railboy** [comment]
I've committed a new change to MRDesignLabs_Unity_Tools that should fix this issue permanently.
