### ISSUE TITLE
Creating BoundingBoxHandle but not interactible

### ISSUE THREAD

**Issue by djrobertjin** [Microsoft/MRDesignLabs_Unity#40]
I am trying to extend the functionality of the module but am running into some roadblocks. I created a new Bounding Box handle via the Unity Editor but it is not recognized as an interactible object. I was wondering if you could point me to where in the code the Interactibles GameObjects List is populated with the Bounding Box Handles. I’ve been trying to debug this for days and to no avail. Any advice or tips would be greatly appreciated.

**Comment by Railboy** [comment]
You can register InteractableObjects with an InteractionReceiver in two ways.

First, in the UnityEditor you can manually drag the gameObject into the InteractionReceiver's _Interactibles_ array. This is how the handles for the Bounding Box are registered.

Second, you can call _InteractionReceiver.RegisterInteractible(GameObject interactible)_ at runtime.

**Comment by djrobertjin** [comment]
Hi, thank you for the response.

I am trying to find where exactly in the editor I can drag it to. It must be right under my nose but I can't seem to pinpoint where to drag it. Is the interaction receiver a component that one of my objects should have?

**Comment by Railboy** [comment]
I should have clarified that the Bounding Box is a special case because it has a custom editor. If you set the inspector mode to Debug you'll be able to see the array in the inspector.

**Comment by Railboy** [comment]
I've updated the Bounding Box inspector to include the Interactibles array.
