### ISSUE TITLE
Mapping surroundings icon no longer displays

### ISSUE THREAD

**Issue by Mustellinus** [Microsoft/MRDesignLabs_Unity#41]
What does it mean when you get the icon in the attached image instead of the usual "trying to map your surroundings icon. The main menu still pops up.
![snapshot 1 8-11-2017 4-03 pm](https://user-images.githubusercontent.com/11513074/29230031-2d995342-7eaf-11e7-8dee-42aac3c77959.png)

**Comment by Mustellinus** [comment]
Rebboting the device corrected the issue ,but I'd still like to know what it means

**Comment by Railboy** [comment]
I'm going to close this since it's a Shell issue and not an MRDesignLabs issue. For shell issues you'll have better luck posting on the [official Hololens forums.](https://forums.hololens.com/)
