### ISSUE TITLE
How to use in Unity Project and keep the project (not git) in sync with this git?

### ISSUE THREAD

**Issue by markleeyw** [Microsoft/MRDesignLabs_Unity#42]
Sorry am quite new to Hololens. 
There is this git which has HoloToolKit and there is HoloToolKit from https://github.com/Microsoft/MixedRealityToolkit-Unity
Which should I be using. 
Also for my Unity project (not git). How to ensure I can get the latest updates from this git? 
Thank you.

**Comment by taylorjames9** [comment]
Hi markleeyw, 

You're right that HoloToolkit appears in these two different locations. The MRTK (Mixed Reality Tool Kit) is still very much in development. It is currently a branch of Holotoolkit github. In the meantime, I recommend downloading the master branch of either MRDesignLabs_Unity (this page), or the main branch of HoloToolkit. If you're new to HoloLens, I recommend getting familiar with HoloToolKit first, and then moving into MRDesignLabs. MRDesignLabs is a more advanced and robust tool, while HoloToolkit is a good confidence builder to get you familiar with many core concepts. 

When you do get into MRDesignLabs_Unity (this page), you can keep the tool up to date by updating the submodule. There are instructions for initializing and updating the submodule on the ReadMe/Front page of MRDesignLabs_Unity (https://github.com/Microsoft/MRDesignLabs_Unity). 

Hope that helps.
