### ISSUE TITLE
Bounding Box Heartbeat on Rotating Object

### ISSUE THREAD

**Issue by DrunkReaperMatt** [Microsoft/MRDesignLabs_Unity#43]
I have an issue where the bounding box surrounding of an object that is in perpetual motion is doing a heartbeat like scaling and it's causing the resacle to be jumpy and buggy when selected.

Is there any type of fix to this?

**Comment by Railboy** [comment]
This is likely due to the Bounds Method setting. It's set to _RendererBounds_ by default. Renderer bounds are in world space so they can cause distortion when rotating an object. Try setting it to _MeshFilterBounds_.

**Comment by DrunkReaperMatt** [comment]
Where does one schange the setting?

**Comment by Railboy** [comment]
You should see it in the inspector:
![inspector](https://user-images.githubusercontent.com/9789716/29287437-4956d11c-80ea-11e7-8671-822894003cf2.PNG)

If you don't see it that means your submodule is out of date. There are instructions for updating the submodule in the[ MRDesignLabs_Unity_Tools readme.](https://github.com/Microsoft/MRDesignLabs_Unity_Tools)

**Comment by DrunkReaperMatt** [comment]
i updated HUX and i have a problem rendering the bounding box proper.

**Comment by Railboy** [comment]
Do you have any details?

**Comment by DrunkReaperMatt** [comment]
When i run the project, when i select my target, the app bar appears but not the bounding box. It does that in the example projects too.

**Comment by Railboy** [comment]
This is a bug that was introduced by the initial prefab state, [described here](https://github.com/Microsoft/MRDesignLabs_Unity/issues/44). A fix has been uploaded.
