### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by markleeyw** [Microsoft/MRDesignLabs_Unity#47]
Hope I'm not doing something wrong. But I tried OnCollisionEnter and OnTriggerEnter to try to detect when one object hits another but its not working. 
Anyone can help?

**Comment by Railboy** [comment]
Since this question isn't specifically related to MRDL I'm going to close this. I'd suggest [Unity Answers](http://answers.unity3d.com/index.html) instead.

**Comment by andy3hg** [comment]
Have u figure out Collision Detection?
I have the same problem.
