### ISSUE TITLE
Question about the direction of rotation (Bounding box)

### ISSUE THREAD

**Issue by alelay** [Microsoft/MRDesignLabs_Unity#48]
Hi everybody,

when I use the Bouding Box with "Flatten Z" in Flattening preference, the rotation handle at the top and the bottom of the box is associated with the Z rotation and not the X rotation (unlike with "Do not flatten" preference). It's a bug or just a choice ? (I tried to explain this with this picture, don't critic my Paint skill :) )

Thanks !
![rotationchelou](https://user-images.githubusercontent.com/27273586/29452491-d8d6dac0-8406-11e7-94ce-dccce8b5c1df.PNG)

**Comment by Railboy** [comment]
Thanks for the illustration. This was a choice. But we're open to feedback if you don't find it intuitive.
