### ISSUE TITLE
Default example DiaglogAndMenuExample has errors.

### ISSUE THREAD

**Issue by markleeyw** [Microsoft/MRDesignLabs_Unity#51]
Tried to run the default scene on Hololens device but getting error. In Unity Editor, no issues running.

Class: HUX.Buttons
Line 132:
currentDatum = Profile.ButtonStates[(int)newState];

Output Debug:
Exception thrown: 'System.NullReferenceException' in Assembly-CSharp.dll

Any fix for this?

**Comment by markleeyw** [comment]
Error only occurs while debugging from VS. Once running the App standalone.. no issues.

**Comment by taylorjames9** [comment]
OK - thanks for the heads up. This isn't the first issue that we're having related to button profiles. We're planning to create a tutorial called "A Primer for Button Profiles" so that people have a good sense of how they're setup and how to use (and debug) them effectively.

**Comment by taylorjames9** [comment]
Hi @markleeyw We're updating some of these features to work with Unity 2017. We've just pushed a change to make the button profiles more stable. Please feel free to try them out now, and let us know if you're still getting null errors related to button profile states.
