### ISSUE TITLE
hide AppBar after use BoundingBox

### ISSUE THREAD

**Issue by Ironfreak** [Microsoft/MRDesignLabs_Unity#53]
Hello, i have a question!
How can i hide the complete "AppBar" after the last tapp, without select an other object ?
Is there a way to set a timout after use to hide the "BoundingBox" and the "AppBar"?

 Thanks!!

**Comment by Railboy** [comment]
A timeout feature is being worked on - expect it soon.

**Comment by Railboy** [comment]
This has been added.
