### ISSUE TITLE
AppBar bug & AppBar Buttons Bigger than Bounding Box (for small objects)

### ISSUE THREAD

**Issue by markleeyw** [Microsoft/MRDesignLabs_Unity#54]
1. I have a few Holographic Buttons, but once I select an item with Bounding Box Target, the Holographic Buttons icons can changed to zoom etc ...  is this a Bug? 

2. For smaller object with Bounding Box Target e.g. A Screw, the App Bar (buttons) seem to appear bigger than the item (Bounding Box). Is there a way to overcome this?

**Comment by Railboy** [comment]
> For smaller object with Bounding Box Target e.g. A Screw, the App Bar (buttons) seem to appear bigger than the item (Bounding Box). Is there a way to overcome this?

For very small items you may want to create a custom prefab. You can scale down the AppBar prefab manually but we don't recommend it. We found that a smaller AppBar was difficult to manipulate / interact with in the HoloLens, so we don't provide any explicit controls.

>I have a few Holographic Buttons, but once I select an item with Bounding Box Target, the Holographic Buttons icons can changed to zoom etc ... is this a Bug?

I need a more detailed description for this one.
