### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by tspaddock** [Microsoft/MRDesignLabs_Unity#57]
Does anyone know if it is possible to use the MR Design Labs bounding box around an imported FBX file parent GameObject and its Children Objects?
I have successfully set it up within my project on just a cube but when I assign the BoundingBoxTarget script to my parent and children GameObjects nothing happens..
Thanks for your help!!

**Comment by Railboy** [comment]
Hi tspaddock - when you say nothing happens, do you mean that nothing happens when you attempt to interact with your object (via tapping or manipulation gestures)?

**Comment by tspaddock** [comment]
Hi,
Sorry Railboy I was on vacation and missed your comment.
To answer your question... what I mean is that when I hand click gesture on a FBX imported asset no bounding box or appbar appears. The asset dose have multiple children elements.
Maybe what would help is if you have a link to a detailed howto installation site/video?
I am able to get the simple cube set up but not a more complex gameobject...
Thanks!
