### ISSUE TITLE
The file "ManipulationManager.cs" is not in "MRDesignLabs_Unity/DesignLabs_Unity/Assets/MRDesignLab/HUX/Scripts/Interaction/".

### ISSUE THREAD

**Issue by TakahiroMiyaura** [Microsoft/MRDesignLabs_Unity#6]
Hi,
I am implementing programs with MRDesignLab.
When using HoloLens.prefab, the ManipulationManager can not be found.
ManipulationManager.cs was not found in "DesignLabs_Unity / Assets / MRDesignLab / HUX / Scripts / Interaction".
However, "ManipulationManager.cs" is in "DesignLabs_Unity_Examples / Assets / MRDesignLab / HUX / Scripts / Interaction".
Should I use "DesignLabs_Unity_Examples/MRDesignLab" ?

![image](https://user-images.githubusercontent.com/8484268/26924829-5625b62a-4c82-11e7-8b80-0b3df739807c.png)

**Comment by Railboy** [comment]
ManipulationManager.cs has been added to DesignLabs_Unity / Assets / MRDesignLab / HUX / Scripts / Interaction & the prefab no longer has a missing script.
