### ISSUE TITLE
AppBar position on Bounding Box Target is off

### ISSUE THREAD

**Issue by mschnabel** [Microsoft/MRDesignLabs_Unity#61]
Hi!

Maybe I am just doing something wrong, but when I use the bounding box target on a simple object like a cube, and the cube is stretched in different directions, the AppBar won't be positioned correctly in relation to the bounding box after I select the object.

Bounds Method is set to "Mesh Filter Bounds". I also tried the other options, but none of them works correctly.

![ezgif-4-1cad565d19](https://user-images.githubusercontent.com/19777233/30629350-9ff1e314-9ddb-11e7-8d6b-76ba273d2fb4.gif)

![2017-09-20_08-11-47](https://user-images.githubusercontent.com/19777233/30629305-6ac3e17e-9ddb-11e7-9aa6-6caf33e91dcd.png)

**Comment by Railboy** [comment]
Hi mschnabel - first off, thanks for the gif capture, those are always helpful.

We're not able to reproduce this behavior. Would you mind sending a snapshot of your scene hierarchy, or (even better) a small example scene?

**Comment by mschnabel** [comment]
Hi!

I've send you a simple Unity project where this kind of behaviour happens. As you will see in the project, I also added HoloToolkit. Maybe this is causing those side effects?

[CubTest.zip](https://github.com/Microsoft/MRDesignLabs_Unity/files/1331832/CubTest.zip)

**Comment by Railboy** [comment]
Excellent, thank you for that scene. We'll investigate this today.

**Comment by Railboy** [comment]
AppBar has been changed to follow the scale of targeted objects more accurately.
