### ISSUE TITLE
AppBar on big objects

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MRDesignLabs_Unity#65]
I have to deal with fairly big objects in our application e.g. 10meters \* 5meters \* 10meters. It's a bit of a challenge to manipulate such big objects but as long as all features are reachable it isn't really an issue. 

The problem I had with the AppBar is that it's really hard to find where it currently is on the huge box. I ended up removing the code that makes it follow the box and used the Tagalong/Billboard combination instead to always have it near the user.

It would be great to have an option for this in the future.

**Comment by Railboy** [comment]
Excellent, glad you found a solution that worked. We'll try to incorporate that into a future version.

We're planning on breaking up the current prefab into several different versions with different behaviors. No single version of the bounding box can be made to work in every case, so we want to encourage developers to do exactly this kind of customization.
