### ISSUE TITLE
Bounding Box for panel

### ISSUE THREAD

**Issue by sancho0410** [Microsoft/MRDesignLabs_Unity#68]
Hi,

I try to use BoundingBoxTarget with panel (rigibody and 2d box collider) but all the time, i have this execution error : 
```
RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).
(Filename: C:\buildslave\unity\build\Runtime/Graphics/RenderTexture.cpp Line: 847)
```
This is normal ? Can i use this script with panel ? 

Thx ;)

**Comment by taylorjames9** [comment]
Hi, We've had several issues with the bounding box come up. We have been in the process of pulling the MRDL codebase into Holotoolkit and updatingit so it can be used for VR+AR development. 

In the course of this transition, we are going back through our sample scenes to clean up several of these features. The bounding box in particular is going to get a fixed up. In the meantime, @railboy may have some insights for fixing this version.

**Comment by Railboy** [comment]
The BoundingBox can be used with panels. Since BoundingBox and BoundingBoxTarget don't make use of RenderTextures, I'm going to guess that this is an unrelated error.
