### ISSUE TITLE
Speech Controller Example

### ISSUE THREAD

**Issue by mitchlotierzo** [Microsoft/MRDesignLabs_Unity#72]
I noticed there are some new scripts in the HUX for dealing with speech. Is there an updated demo for how to use those or are we still using SpeechInputSource and SpeechInputHandler?

**Comment by paseb** [comment]
Hi @mitchlotierzo,

The speech scripts were an older part of the toolkit and will be refactored and either added to MRTK or updated with some examples in MRDL.  We're currently waiting for the initial merger of MRDL base functionality and MRTK.

PR: https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1197

thanks,
-pat
