### ISSUE TITLE
BoundingBox Scale Handles Reverse from certain angles and positions

### ISSUE THREAD

**Issue by freekpixels** [Microsoft/MRDesignLabs_Unity#73]
Hello!
First of all, amazing work guys, hope to be able to contribute asap!
The issue I am raising here is about the BoundingBox scale witch seems to have an issue with it's handles and their reversing when scaling(to get the right scaling direction).

Here is a recording of what happens with the MRDL Manipulation Example deployed in a HoloLens. The same thing happens in our app as well but for showing the problem the unchanged example was used.

[https://youtu.be/GEXGHyER2AU](url)

I am happy to answer any questions that can help understand the issue!

Thank you!

**Comment by Railboy** [comment]
Thanks for the video - visual aids are always appreciated!

This issue is fixed in an upcoming version - we'll be posting a branch for testing the new bounding box soon.

**Comment by freekpixels** [comment]
Amazing! Thank you!
