### ISSUE TITLE
Deprecated namespaces InputSourceHands and InputManager in Unity 2017.2

### ISSUE THREAD

**Issue by Tanja-L** [Microsoft/MRDesignLabs_Unity#77]
When updating to Unity 2017.2, Unity throws multiple error messages. Unity.VR.WSA has been changed to Unity.XR.WSA. I had to fix some of these errors manually. The event names in InputSourceHands are also obsolete but it's possible to use for example "UnityEngine.XR.WSA.Input.InteractionManager.InteractionSourceDetectedLegacy", although Unity shows warnings that this is obsolete and will be removed in future releases.
Will there be an updated version for the latest Unity Version?

**Comment by paseb** [comment]
There already is and it's the branch that has been updated.  If you're using the master branch you're not using the correct one for Unity 2017.2.  Please use this branch:
- https://github.com/Microsoft/MRDesignLabs_Unity/tree/Unity2017.2-Dev

We are in the process of merging functionality with MRTK and once that is complete we will merge back in MRTK over HoloToolkit.  The 2017.2 branch is up to date and should run without any errors.

thanks,
-pat

**Comment by Tanja-L** [comment]
Thanks, I didn't see the second branch
