### ISSUE TITLE
master vs Unity2017.2-Dev submodule folders

### ISSUE THREAD

**Issue by oshea00** [Microsoft/MRDesignLabs_Unity#78]
When I checkout the Unity2017.2-Dev branch, the submodule "mount" points under each of the unity project folders are named "MRDesignLabs".
In the master branch these are named "MRDesignLab".

This a problem when loading the unity projects as now there are two Design Lab folders. To work around this once I noticed what's happening:
1. checkout Unity2017.2-Dev branch in locally cloned repo.
2. run:
git submodule update --init --recursive
3. manually remove the "MRDesignLab" folders - leaving the "MRDesignLabs" folders.
4. Re-import assets in unity.
5. Fix the missing using statement referenced in the 7 compile errors.

**Comment by cre8ivepark** [comment]
@paseb @Railboy Could you please share information about this updated submodule name?

**Comment by paseb** [comment]
The name should not have changed.  Let me double check this.

**Comment by paseb** [comment]
I fixed the namespace issues in the branches.  This should be resolved.  Please let me know if you're still having issues.

thanks,
- pat
