### ISSUE TITLE
ManipulationGizmo_Examples Scene: Failed to get pointer position source ID:0

### ISSUE THREAD

**Issue by oshea00** [Microsoft/MRDesignLabs_Unity#80]
Built the ManipulationGizmo_Examples using the Unity2017.2-Dev branch (see issue #79)
I'm using the latest Windows 10 update (10.0.16299) w/ Fall Creators Update SDK.
Running in Hololens Emulator 10.0.14393.1358. Running under VS 2017 15.4.1.

The app starts up the emulator, but any click/select gesture on the scene objects generates this error:
Failed to get pointer position source ID: 0
 (Filename: C:\buildslave\unity\build\artifacts/generated/Metro/runtime/DebugBindings.gen.cpp Line: 51)
The App bar doesn't appear.

**Comment by oshea00** [comment]
Digging into code found that the InteractionManager InputSource type is not returning a position. Looked at available InputSource*.cs scripts in Hux/Scripts/Input and added InputSourceWorldCursorHands.  Seems like this example is not tested with Hololens much. Adding the InputSource allowed me to activate the menubar, but still other wierd problems. My guess is more code is needed to work well with Hololens...

**Comment by blo85** [comment]
@oshea00 Could you finally use the boundingbox to manipulate any object with Hololens? Can you please explain your InputSourceWorldCursorHands solution a little more in detail?

BR

**Comment by filsv** [comment]
Support @blo85 , @oshea00 can you explain how you fixed it? thank you.
