### ISSUE TITLE
Hardcoded paths in HUXEditorMenu.cs in DesignLabs_Unity_Examples project

### ISSUE THREAD

**Issue by oshea00** [Microsoft/MRDesignLabs_Unity#81]
In the Unity2.0-Dev branch DesignLabs_Unity_Examples project, there are hardcoded paths to various project assets. Since the MRDesignLab folder is now MRDesignLabs (plural) in this branch, stuff is broken.

**Comment by paseb** [comment]
I updated the folder to keep the old name as the name change was in intentional.  Should be resolved now.
