### ISSUE TITLE
The name 'WorldAnchorStore' does not exist in the current context

### ISSUE THREAD

**Issue by steuhh** [Microsoft/MRDesignLabs_Unity#83]
Hi !

I get this weird issue when trying to build:

Assets\MRDesignLab\HUX\Scripts\Spatial\PointOfReferenceManager.cs(64,9): error CS0103: The name 'WorldAnchorStore' does not exist in the current context

Just commenting this out works. Is there a more elegant solution ?

**Comment by paseb** [comment]
We'll be removing that with the refactor and upgrade to MRTK over the previous HoloToolkit version currently in the projects.

thanks,
-pat
