### ISSUE TITLE
Scaling on X,Y,Z does not work for Manipulation Gizmo Scene

### ISSUE THREAD

**Issue by voonfoo98** [Microsoft/MRDesignLabs_Unity#90]
I want to scale and rotate my object using AppBar and Bounding Box Target. However, when i ticked the Scale X, Y, Z properties on BoundingBoxtarget, InteractionManager, it still does not work.

Can anyone guide me on how to Scale Object X,Y,Z in Manipulation Gizmo Scene?

**Comment by cre8ivepark** [comment]
@voonfoo98 Please check out new Bounding Box and App Bar in MRTK's Dev branch.
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md
