### ISSUE TITLE
Failed to get pointer position source ID: 0

### ISSUE THREAD

**Issue by filsv** [Microsoft/MRDesignLabs_Unity#93]
Hi, I'm trying to add Bounding Box + App Bar to a 3D object, it's doesn't work for me.

Everything from this tutorial: https://github.com/StephenHodgson/MRDesignLabs_Unity/tree/master/DesignLabs_Unity_Examples#app-bar--bounding-box

I'm using Unity 2017.1.0f3 and "MixedRealityToolkit-Unity & MRDesignLabs_Unity".
I also tried latest Unity 2017.3.1f1 with "Unity-2017.2-Dev" branch.

Maybe I'm doing something wrong, please help.

**By steps:**

1) "Adding Hololens Prefab":

<img width="1440" alt="screen shot 2018-02-24 at 19 05 38" src="https://user-images.githubusercontent.com/13712013/36632956-ee0c112e-1995-11e8-9071-ccb9a9bd2e80.png">

<img width="1440" alt="screen shot 2018-02-24 at 19 06 33" src="https://user-images.githubusercontent.com/13712013/36632989-6917bdbe-1996-11e8-8da9-2f6cff201ca7.png">

2) "Adding 3D Object - Sphere":
<img width="1440" alt="screen shot 2018-02-24 at 19 05 49" src="https://user-images.githubusercontent.com/13712013/36632964-0d17e4da-1996-11e8-8ae5-f9122c650755.png">

3) "Applying Bounding Box Target" on this object:
<img width="1440" alt="screen shot 2018-02-24 at 19 06 08" src="https://user-images.githubusercontent.com/13712013/36632970-1c1f856e-1996-11e8-94aa-0adefd585945.png">

Project hierarchy:
<img width="1440" alt="screen shot 2018-02-24 at 19 06 33" src="https://user-images.githubusercontent.com/13712013/36632991-7d0d74e4-1996-11e8-9694-b2dee527b5a7.png">

The result, when I'm tapping on the My object with Bounding Box Target, I'm getting:

<img width="1440" alt="screen shot 2018-02-24 at 19 20 33" src="https://user-images.githubusercontent.com/13712013/36633099-015a3ff6-1998-11e8-85d0-c29a80109c1a.png">
Log Warning: "Failed to get pointer position source ID: 0". (from InteractionManager.cs line 975).

What I'm doing wrong, or what I need to attach to make it works?

Thank you.

**Comment by cre8ivepark** [comment]
@filsv Hi, we have ported Bounding Box and App Bar to MRTK. It works with the latest MRTK Dev_Working_Branch. Please check this pull request:
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1785

**Comment by cre8ivepark** [comment]
@filsv Bounding Box and App Bar is now merged in MRTK's Dev branch.
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md
